# Generated by Django 5.2.5 on 2025-09-06 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='films/posters/')),
                ('trailer_url', models.URLField(blank=True, help_text='External link (YouTube, Vimeo, etc.)', null=True)),
                ('trailer_file', models.FileField(blank=True, help_text='Optional self-hosted trailer file.', null=True, upload_to='films/trailers/')),
                ('video_file', models.FileField(blank=True, help_text='Original high-quality video file.', null=True, upload_to='films/videos/')),
                ('hls_manifest', models.FileField(blank=True, help_text='Path to the HLS .m3u8 manifest file.', null=True, upload_to='films/hls/')),
                ('status', models.CharField(choices=[('promo', 'Promo'), ('paid', 'Paid')], default='paid', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Price in KES (e.g., 500.00 for KES 500)', max_digits=10)),
                ('rental_period_days', models.PositiveIntegerField(default=2)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('processing_log', models.TextField(blank=True, help_text='Optional log/debug info from encoding pipeline.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='films', to='films.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
