# Generated by Django 5.2.5 on 2025-09-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='hls_manifest',
            field=models.FileField(blank=True, null=True, upload_to='films/hls/'),
        ),
        migrations.AlterField(
            model_name='film',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='film',
            name='processing_log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='trailer_file',
            field=models.FileField(blank=True, null=True, upload_to='films/trailers/'),
        ),
        migrations.AlterField(
            model_name='film',
            name='trailer_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='films/videos/'),
        ),
    ]
