# Generated by Django 5.2.5 on 2025-09-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_film_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='price',
        ),
        migrations.AddField(
            model_name='film',
            name='hls_manifest_path',
            field=models.CharField(blank=True, default='', help_text='Path to the HLS .m3u8 manifest file.', max_length=512),
        ),
        migrations.AddField(
            model_name='film',
            name='price_cents',
            field=models.PositiveIntegerField(default=0, help_text='Price in KES cents (e.g., 50000 for KES 500.00)'),
        ),
        migrations.AlterField(
            model_name='film',
            name='trailer_url',
            field=models.URLField(blank=True, help_text='Link to the trailer on YouTube, Vimeo, etc.', null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='video_file',
            field=models.FileField(blank=True, help_text='The original high-quality video file.', null=True, upload_to='films/videos/'),
        ),
    ]
