# Generated by Django 5.2.5 on 2025-09-06 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_request_id', models.CharField(max_length=100, unique=True)),
                ('merchant_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('result_code', models.IntegerField(blank=True, null=True)),
                ('result_desc', models.TextField(blank=True, null=True)),
                ('amount_cents', models.PositiveIntegerField(blank=True, help_text='Amount in KES cents', null=True)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.PositiveIntegerField(help_text='Payout amount in KES cents')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, help_text='M-Pesa Transaction ID for the payout.', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe'), ('mpesa', 'M-Pesa')], max_length=10)),
                ('amount_cents', models.PositiveIntegerField(help_text='Total amount paid in KES cents')),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('payment_id', models.CharField(blank=True, help_text='Stripe session ID or M-Pesa CheckoutRequestID', max_length=255, null=True)),
                ('transaction_id', models.CharField(blank=True, help_text='Final M-Pesa Transaction ID', max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Customer phone for M-Pesa', max_length=15, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('access_expires_at', models.DateTimeField(blank=True, null=True)),
                ('platform_fee_cents', models.PositiveIntegerField(default=0)),
                ('filmmaker_payout_cents', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='films.film')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
