# Generated by Django 5.2.5 on 2025-09-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='filmmaker_payout',
        ),
        migrations.RemoveField(
            model_name='order',
            name='platform_fee',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='amount',
        ),
        migrations.AddField(
            model_name='order',
            name='amount_cents',
            field=models.PositiveIntegerField(default=0, help_text='Total amount paid in KES cents'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='filmmaker_payout_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='platform_fee_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='amount_cents',
            field=models.PositiveIntegerField(blank=True, help_text='Amount in KES cents', null=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='amount_cents',
            field=models.PositiveIntegerField(default=1, help_text='Payout amount in KES cents'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Final M-Pesa Transaction ID', max_length=100, null=True),
        ),
    ]
