# Generated by Django 5.2.5 on 2025-09-04 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_email_verified_customuser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mpesa_payout_number',
            field=models.CharField(blank=True, help_text='The M-Pesa number for receiving payouts.', max_length=15, null=True),
        ),
    ]
