# Generated by Django 5.2.5 on 2025-09-03 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmmakers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmmakerapplication',
            name='portfolio_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
