# Generated by Django 5.2.5 on 2025-09-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmmakers', '0002_alter_filmmakerapplication_portfolio_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmmakerapplication',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='filmmakerapplication',
            name='portfolio_link',
        ),
        migrations.AddField(
            model_name='filmmakerapplication',
            name='previous_works_links',
            field=models.TextField(blank=True, help_text='Links to your previous films.'),
        ),
        migrations.AddField(
            model_name='filmmakerapplication',
            name='reasons',
            field=models.TextField(default='', help_text='Why do you want to join Mbogiwood?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filmmakerapplication',
            name='showreel_link',
            field=models.URLField(blank=True),
        ),
    ]
