# Generated by Django 5.2.5 on 2025-09-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagecontent',
            name='countries_reached',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='films_featured',
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='hours_watched',
            field=models.CharField(default='1M', max_length=20),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='professionals_connected',
            field=models.CharField(default='10K', max_length=20),
        ),
    ]
