# Generated by Django 5.2.5 on 2025-09-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_aboutpagecontent_countries_reached_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagecontent',
            name='our_values',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='vision_statement',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='countries_reached',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='films_featured',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='hours_watched',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='mission_statement',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='our_story',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='professionals_connected',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
